apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: giropops-senhas
  namespace: argocd
spec:
  destination:
    namespace: giropops-senhas
    server: 'https://kubernetes.default.svc'
  project: 'default'
  source:
    helm: {}
    repoURL: 'https://github.com/renatoDev0ps/descomplicando-gitops-no-kubernetes-argocd.git'
    targetRevision: feat/day2
    path: giropops-senhas/helm
  syncPolicy:
    automated: {}